version: '3'
services:
  manager:
    build: ./backend
    command: npm run start:manager
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
    networks:
      - crackhash-network
    depends_on:
      - mongodb
      - rabbitmq


  worker1:
    build: ./backend
    command: npm run start:worker
    env_file:
      - .env
    environment:
      - PORT=3001
    networks:
      - crackhash-network
    depends_on:
      - rabbitmq


  worker2:
    build: ./backend
    command: npm run start:worker
    env_file:
      - .env
    environment:
      - PORT=3002
    networks:
      - crackhash-network
    depends_on:
      - rabbitmq


  worker3:
    build: ./backend
    command: npm run start:worker
    env_file:
      - .env
    environment:
      - PORT=3003
    networks:
      - crackhash-network
    depends_on:
      - rabbitmq


  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - manager
    networks:
      - crackhash-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017" 
    networks:
      - crackhash-network


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - crackhash-network

networks:
  crackhash-network:
    driver: bridge