version: '3'
services:
  manager:
    build: ./backend
    command: npm run start:manager
    ports:
      - "3000:3000"
    depends_on:
      worker1:
        condition: service_healthy
      worker2:
        condition: service_healthy
      worker3:
        condition: service_healthy
    networks:
      - crackhash-network

  worker1:
    build: ./backend
    command: npm run start:worker
    environment:
      - PORT=3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crackhash-network

  worker2:
    build: ./backend
    command: npm run start:worker
    environment:
      - PORT=3002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crackhash-network

  worker3:
    build: ./backend
    command: npm run start:worker
    environment:
      - PORT=3003
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crackhash-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - manager
    networks:
      - crackhash-network

networks:
  crackhash-network:
    driver: bridge
