version: '3'
services:
  manager:
    build: ./backend
    command: npm run start:manager
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
    networks:
      - crackhash-network

  worker1:
    build: ./backend
    command: npm run start:worker
    env_file:
      - .env
    environment:
      - PORT=3001
    networks:
      - crackhash-network

  worker2:
    build: ./backend
    command: npm run start:worker
    env_file:
      - .env
    environment:
      - PORT=3002
    networks:
      - crackhash-network

  worker3:
    build: ./backend
    command: npm run start:worker
    env_file:
      - .env
    environment:
      - PORT=3003
    networks:
      - crackhash-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - manager
    networks:
      - crackhash-network

networks:
  crackhash-network:
    driver: bridge